### ISSUE TITLE
[help wanted] Adding Username and Password list

### ISSUE THREAD

**Issue by UgaBugaBoo** [frostysecurethebag/NightMarket-Checker#1]
Is it possible to add an option so that I can inject my own username and passwords in it so that it can output everything at one run ?

**Comment by UgaBugaBoo** [comment]
Sorry for missing the about section, it says I can do bulk check. Since I am new to python can't really figure out how to do so. Could you please assist me in this case ?

**Comment by frostysecurethebag** [comment]
I actually had uploaded the wrong py file, I have updated it including the readme which now includes how to use, let me know if you need any help

**Comment by UgaBugaBoo** [comment]
> I actually had uploaded the wrong py file, I have updated it including the readme which now includes how to use, let me know if you need any help

I have used the new version and it has been working well. 
![image](https://user-images.githubusercontent.com/7885525/135879635-7faa75a3-b2f3-4f7b-b385-8624170b6322.png)


One request though, if could be output to curated csv file that would make it perfect. 

With me zero knowledge I was trying it but failing hard on remove that { on first item name : 
![image](https://user-images.githubusercontent.com/7885525/135879890-f87ce801-dabb-4885-8e77-798d35cd4c35.png)

**Comment by frostysecurethebag** [comment]
looks like a great idea ill try asap

**Comment by UgaBugaBoo** [comment]
> looks like a great idea ill try asap

Thanks a ton for adding it, trying it right away

**Comment by UgaBugaBoo** [comment]
> > looks like a great idea ill try asap
> 
> Thanks a ton for adding it, trying it right away

@frostysecurethebag Well it doesn't seem to be outputting to the CSV file. 

![image](https://user-images.githubusercontent.com/7885525/135892882-46533c59-2377-4aab-8599-9d1f87832917.png)

**Comment by UgaBugaBoo** [comment]
My bad it outputs after the py windows is closed

**Comment by UgaBugaBoo** [comment]
@frostysecurethebag it seems it's calling the https://valorant-api.com/v1/weapons/skinlevels/ api for every skin and it's taking quite long time and consuming more data. Isn't it possible to store the entire endpoint to a file and call from that ?

**Comment by UgaBugaBoo** [comment]
It's taking quite a bit of time it seems, also I guess RIOT blocks the IP after certain amount of logins within a certain time window. @frostysecurethebag

**Comment by UgaBugaBoo** [comment]
Also for better usability in Excel this formatting should be a better option:

'Account', 'Offer-Item1' , 'Discount-Percent1" , 'Offer-Item2' , 'Discount-Percent2" , 'Offer-Item3' , 'Discount-Percent3" , ........
