### ISSUE TITLE
[feature request] Bulk account creator?

### ISSUE THREAD

**Issue by saifeealii** [frostysecurethebag/NightMarket-Checker#3]
Hi, i am very grateful for the work you have done here. can you create another script for automating the processing of creating new accounts? Like we can just create a text file of a list of email;birthdate;user;pass. Since the list can easily be generated so the process will be a whole lot easy to create accounts in bulk. so, then we can check their night markets to spot nice accounts.

**Comment by UgaBugaBoo** [comment]
> Hi, i am very grateful for the work you have done here. can you create another script for automating the processing of creating new accounts? Like we can just create a text file of a list of email;birthdate;user;pass. Since the list can easily be generated so the process will be a whole lot easy to create accounts in bulk. so, then we can check their night markets to spot nice accounts.

I don't think it's possible to do it from just CMD

**Comment by saifeealii** [comment]
> > Hi, i am very grateful for the work you have done here. can you create another script for automating the processing of creating new accounts? Like we can just create a text file of a list of email;birthdate;user;pass. Since the list can easily be generated so the process will be a whole lot easy to create accounts in bulk. so, then we can check their night markets to spot nice accounts.
> 
> I don't think it's possible to do it from just CMD

it can be done with browser automation maybe.

**Comment by UgaBugaBoo** [comment]
> > > Hi, i am very grateful for the work you have done here. can you create another script for automating the processing of creating new accounts? Like we can just create a text file of a list of email;birthdate;user;pass. Since the list can easily be generated so the process will be a whole lot easy to create accounts in bulk. so, then we can check their night markets to spot nice accounts.
> > 
> > 
> > I don't think it's possible to do it from just CMD
> 
> it can be done with browser automation maybe.

I think there was a project where you could do with Browser Extension [automation]

**Comment by frostysecurethebag** [comment]
Botting accounts looks bannable ( maybe ), but if you still want to farm accounts you could use something like selenium or  puppeteer  :)
