### ISSUE TITLE
nm checker issue

### ISSUE THREAD

**Issue by faizanhasnain** [frostysecurethebag/NightMarket-Checker#5]
i am getting issue in this checker as shown in pictur
![Screenshot_1](https://user-images.githubusercontent.com/87815652/153387888-e10588e2-ff44-4bfb-8706-0eeb663bd1bf.png)
e

**Comment by frostysecurethebag** [comment]
you can either run "pip install -r requirements.txt" in your terminal to install all the required modules 
or run "pip install cloudscraper", "pip install requests" in your terminal.

**Comment by faizanhasnain** [comment]
dude i cant understand what are u trying to say :(
