### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dwayne-lifter** [frostysecurethebag/NightMarket-Checker#6]
I'm getting this error : )

> E:\Projects\Python\Valorant\NightMarket Checker>python nmchecker.py
> ------------------------------------------------------------------------------------------------------------------------------------------------------
>  Traceback (most recent call last):
>   File "E:\Projects\Python\Valorant\NightMarket Checker\nmchecker.py", line 135, in <module>
>     main()
>   File "E:\Projects\Python\Valorant\NightMarket Checker\nmchecker.py", line 125, in main
>     token = getToken(acc[0], acc[1])
> IndexError: list index out of range

**Comment by frostysecurethebag** [comment]
Use semi colon (;) to differentiate the username and password in your text file
